### PR TITLE
Added electrolab laser cut visor, faster and cheaper

### PR DESCRIPTION
**Pull request by l-henri**
Adding a new visor model, which ships fast and cheaply.
My ETH address is 0xdBdF0A42Ee6809E4C4350F99539e91B91b4ae4b0

### CODE REVIEW

**Comment by bneiluj** [comment]
can you please fix the conflicts first ?

**Comment by l-henri** [comment]
That should do it!

**Comment by bneiluj** [comment]
Reward to be sent: $5 worth of DAI or USDC
Ethereum Address: 0xdBdF0A42Ee6809E4C4350F99539e91B91b4ae4b0

**Comment by bneiluj** [comment]
5 DAI reward sent to 0xdBdF0A42Ee6809E4C4350F99539e91B91b4ae4b0 
https://etherscan.io/tx/0xf72ac1c408a8ff61a71205135fd29e87e81e7df3381c4af0e75019cc776b6a80

**Pull request merged**
